

```{r}
exdata <- read.csv(file = 'SV_y.csv')
y <- exdata$X0
n <- 1562
time <- c(1:1562)   
```

```{r}
png('SV_y.png',width=400, height=200, units='mm', res=300)
plot(time,y, type="l")
abline(h=0)
dev.off()
```

```{r}
f <- function(x){
  nt <- n
  sig_ep  <- pi^2/2                   # process err variance
  sig_eta  <- x[1]                    # obs error variance
  T <- x[2]
  a <- rep(0,nt)
  P <- rep(0,nt)

  
  v <- rep(0,nt)
  F <- rep(0,nt)
  K <- rep(0,nt)
  
  
  a[1] <- 0
  P[1] <- 10^10


  v[1] <- log(y[1]^2)+1.2704 - a[1]
  F[1] <- P[1] + sig_ep
  K[1] <- T * P[1]/F[1]
  
  
  for(t in 2:nt){
    a[t] <- T * a[t-1] + K[t-1]*v[t-1]
    P[t] <- T * P[t-1]*(T-K[t-1]) + sig_eta
    
    
    v[t] <- log(y[t]^2) + 1.2704 - a[t]
    F[t] <- P[t] + sig_ep
    K[t] <- T * P[t]/F[t]
  }
  
  FF <- F[c(2:nt-1)]
  vv <- v[c(2:nt-1)]
  return(sum(log(FF))+sum(vv^2/FF))
}
```



```{r}
library('nloptr')
res1 <- nloptr( x0=c(0,1),
                eval_f=f,
                lb = c(0,-1),
                ub = c(Inf,1),
                opts = list("algorithm"="NLOPT_LN_COBYLA"),
)
print( res1 )
```

```{r}
  nt <- n
  sig_ep  <- pi^2/2                   # process err variance
  sig_eta  <- 0.002979168             # obs error variance
  T <- 0.9999972
  a <- rep(0,nt)
  P <- rep(0,nt)

  
  v <- rep(0,nt)
  F <- rep(0,nt)
  K <- rep(0,nt)
  
  
  a[1] <- 0
  P[1] <- 10^10


  v[1] <- log(y[1]^2)+1.2704 - a[1]
  F[1] <- P[1] + sig_ep
  K[1] <- T * P[1]/F[1]
  
  
  for(t in 2:nt){
    a[t] <- T * a[t-1] + K[t-1]*v[t-1]
    P[t] <- T * P[t-1]*(T-K[t-1]) + sig_eta
    
    
    v[t] <- log(y[t]^2) + 1.2704 - a[t]
    F[t] <- P[t] + sig_ep
    K[t] <- T * P[t]/F[t]
  }
  hatalp <- rep(0,nt)
  V <- rep(0,nt)
  r <- rep(0,nt+1)
  N <- rep(0,nt+1)
  
  r[nt] <- 0
  hatalp[nt] <- a[nt]
  N[nt] <- 0
  V[nt] <- 0
  
  for (k in 1:nt){
    m <- nt-k+1
    r[m] <- v[m]/F[m]+(T-K[m])*r[m+1]
    hatalp[m]<-a[m]+P[m]*r[m]
    N[m] <- 1/F[m]+(T-K[m])^2*N[m+1]
    V[m] <- P[m]-P[m]^2*N[m]
  }
```


```{r}
png('SV_hatalp.png',width=400, height=150,units='mm', res=300)
plot(time[c(2:nt-1)], hatalp[c(2:nt-1)], type="l", col="red")
points(time[c(2:nt-1)], (log(y^2) + 1.2704)[c(2:nt-1)],pch = 16)
dev.off()

  
```

